development: &default
  adapter: postgresql
  encoding: unicode
  database: jail_dashboard_dev
  pool: 5
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

# test:
#   <<: *default
#   database: jail_dashboard_test

test:
  adapter: postgresql
  database: travis_ci_test
