default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: jail_dashboard_dev

test:
  <<: *default
  database: travis_ci_test

production:
  <<: *default
  database: jail_dashboard_prod
