development: &default
  adapter: postgresql
  encoding: unicode
  database: jail_dashboard_dev
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: jail_dashboard_test
